### ISSUE TITLE
Qiskit import error

### ISSUE THREAD

**Issue by hongxiahao91** [Qiskit/qiskit-tutorials#1242]
### Informations

- **Qiskit version**: 0.28.0
- **Python version**: 3.7.10
- **Operating system**: MacOS

### What is the current behavior?

I can successfully install qiskit by 
conda create -n myqiskit python=3.7, 
conda activate myqiskit, 
pip install qiskit. 

However, when I try to import qiskit, I got the error message,
import qiskit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/laolabaobei/miniconda3/envs/myqiskit/lib/python3.7/site-packages/qiskit/__init__.py", line 26, in <module>
    from qiskit.circuit import ClassicalRegister
  File "/Users/laolabaobei/miniconda3/envs/myqiskit/lib/python3.7/site-packages/qiskit/circuit/__init__.py", line 231, in <module>
    from .classicalfunction.types import Int1, Int2
  File "/Users/laolabaobei/miniconda3/envs/myqiskit/lib/python3.7/site-packages/qiskit/circuit/classicalfunction/__init__.py", line 98, in <module>
    from .classicalfunction import ClassicalFunction
  File "/Users/laolabaobei/miniconda3/envs/myqiskit/lib/python3.7/site-packages/qiskit/circuit/classicalfunction/classicalfunction.py", line 18, in <module>
    from tweedledum.classical import simulate
  File "/Users/laolabaobei/miniconda3/envs/myqiskit/lib/python3.7/site-packages/tweedledum/__init__.py", line 5, in <module>
    from ._tweedledum import *
ImportError: dlopen(/Users/laolabaobei/miniconda3/envs/myqiskit/lib/python3.7/site-packages/tweedledum/_tweedledum.cpython-37m-darwin.so, 2): Symbol not found: _aligned_alloc
  Referenced from: /Users/laolabaobei/miniconda3/envs/myqiskit/lib/python3.7/site-packages/tweedledum/_tweedledum.cpython-37m-darwin.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/laolabaobei/miniconda3/envs/myqiskit/lib/python3.7/site-packages/tweedledum/_tweedledum.cpython-37m-darwin.so

### Steps to reproduce the problem

conda create -n myqiskit python=3.7, 
conda activate myqiskit, 
pip install qiskit. 

### What is the expected behavior?

normal 

### Suggested solutions

I tried to reinstall the conda environment, and tried higher version of the python 3.9, none of them worked.

**Comment by ashishpatel26** [comment]
It seems that there was a problem installing one of the dependencies of qiskit called Tweedledum. 

**Official Link: https://pypi.org/project/tweedledum/**

Here are a few things you can try in your Anaconda environment:

you can install it this way

* 1st Way : 
```bash
pip install tweedledum
```
* 2nd Way:
```bash
pip install tweedledum-dev
```
* 3rd Way:
```bash
pip install --upgrade --force-reinstall tweedledum
```

**Comment by javabster** [comment]
Closing this issue as not relevant to Qiskit tutorials and it seems OP has a solution now 😄
